spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=g130ministoredb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/changelog.xml